
  {{MODULE_PASCAL}}Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: {{MODULE}}/index.handler
      Timeout: 60
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - !Ref LambdaSharedPolicy
      Events:
        