name: DEPLOY DOMAIN
"on":
  push:
    branches:
      - develop
    paths: 
      - domain

  pull_request:
    types: [closed, opened, edited]
    branches:
      - develop
      - main
    paths: 
      - domain
  

  workflow_dispatch:

env:
  SKO_PREDICTION_EDITING_WINDOW: ${{ vars.SKO_PREDICTION_EDITING_WINDOW }}

jobs:
  
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: NAME
        run: |
          echo 'github.ref ${{ github.ref }}'
          echo 'github.event ${{ toJson(github.event) }}'
          echo 'github.event_name ${{ github.event_name }}'
          echo 'github.event.pull_request ${{ github.event.pull_request }}'
          echo 'github.event.pull_request.action ${{ github.event.pull_request.action }}'

      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SETUP NODE
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com


      - name: INSTALL PNPM
        run: |
          npm install -g pnpm


      - run: |
          cd domain
          pnpm i
          pnpm run build:deploy

      - run: |
          cd domain
          cd dist
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEPLOYMENT_DOMAIN_TOKEN }}

   
   