name: Skorify Frontend CI

on:
  push:
    branches: [ test/build-workflow ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:

  # ── Build (solo si lint pasa) ─────────────────────────
  build:
    name: Build
    # needs: lint
    uses: aws-ug-manizales/Skorify_DevOps/.github/workflows/build-backend.yml@feat/build--workflow
    with:
      node-version: '22'
    secrets: inherit